name: Python Package with dependencies managed by pip

on: [push]

jobs:
  build-env:
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.11"]
        java-version: ["21"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    - run: java HelloWorldApp.java

    - name: Install dependencies
      run: |
        make install

    - name: Run tests
      run: |
        make test lint

    - name: flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --extend-exclude snpEff --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run validation & test results
      run: |
        ./run_test_workflow.sh

