name: Python Package with dependencies managed by pip

on: [push]

jobs:
  build-env:
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install snpEff
      run: |
        wget https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip
        unzip snpEff_latest_core.zip

    - name: Install other dependencies with pip
      run: pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --extend-exclude snpEff --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run validation & tests
      run: echo "Done setting up the environment. Let's run some tests..."
