name: Python Package using Mamba

on: [push]

jobs:
  build-env:
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - name: Set up Mamba-Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
    - shell: bash -l {0}
      run: conda info

    - name: Install dependencies
      run: |
        mamba install pandas
        mamba install sqlite
        mamba install -c bioconda snpEff
        mamba install pytest
    - name: Lint with flake8
      run: |
        mamba install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

   
