name: Python Package with dependencied managed by Conda

on: [push]

jobs:
  build-env:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10"]

    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: whatever
          python-version: ${{ matrix.python-version }}

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Install dependencies
        run: |
          conda install -c anaconda pandas
          conda install -c bioconda snpEff
          conda install pytest
          conda install flake8
          conda list

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          which flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: run validation & tests
        run: bash ./test_workflow_bare-bones.sh
